### ISSUE TITLE
A bug considering the version of gensim

### ISSUE THREAD

**Issue by hliuw** [samoturk/mol2vec_notebooks#1]
Good evening sir,

I installed the mol2vec package and tried to run this notebook. However it worked neither on gensim=3.4.0(latest and is automatically installed with mol2vec) nor on gensim=3.0.1(as suggested in the requirement.txt). It turned out to be some function missing or may have a different name.

I tried several version and finally it worked out with gensim=3.1.0. I wonder if it is a typo in the requirement.txt .

**Comment by samoturk** [comment]
Thanks for pointing this out. I fixed the notebook now.
