### ISSUE TITLE
How to generate depictions.pkl file?

### ISSUE THREAD

**Issue by XinhaoLi74** [samoturk/mol2vec_notebooks#2]
Hi, 
I am really interested in this interactive t-sne plot. Could you explain more about how to generate the depictions.pkl file? Thanks

**Comment by samoturk** [comment]
I used some custom code to highlight the atoms belonging to certain fingerprint, but I don't seem to find it anymore. RDKit now also supports similar, so please check this: https://rdkit.readthedocs.io/en/latest/GettingStartedInPython.html#generating-images-of-fingerprint-bits
